from pathlib import Path
path = Path('frontend/src/ui-editor/pages/CanvasWorkspace.jsx')
text = path.read_text(encoding='utf-8')
lines = text.splitlines()
start = next(i for i,l in enumerate(lines) if '<CanvasScreenSelector' in l) - 1
end = next(i for i,l in enumerate(lines) if '          <PropertiesPanel' in l)
new_lines = [
"            <CanvasScreenSelector",
"              screens={screens}",
"              selectedScreenId={activeScreen?.id ?? ''}",
"              onSelectScreen={setSelectedScreenId}",
"            />",
"",
"          </div>",
"",
"          <div className=\"editor-home__status-stack\">",
"            <section",
"              className={`ui-editor__status editor-home__status-panel ui-editor__status--${status.phase === 'idle' ? 'loading' : status.phase}`}",
"              aria-live=\"polite\"",
"            >",
"              <strong>Status:</strong> {status.message}",
"            </section>",
"",
"            <section",
"              className={`canvas-workspace__publish-status canvas-workspace__publish-status--${publishState.status}`}",
"              aria-live=\"polite\"",
"            >",
"              <div className=\"canvas-workspace__publish-status-message\">{publishState.message}</div>",
"              {publishMeta ? (",
"                <dl className=\"canvas-workspace__publish-meta\">",
"                  <div>",
"                    <dt>Generated</dt>",
"                    <dd>{formatPublishTimestamp(publishMeta.generatedAt)}</dd>",
"                  </div>",
"                  <div>",
"                    <dt>Routes</dt>",
"                    <dd>{publishMeta.routeCount ?? '--'}</dd>",
"                  </div>",
"                  <div>",
"                    <dt>Screens</dt>",
"                    <dd>{publishMeta.screenCount ?? '--'}</dd>",
"                  </div>",
"                  {publishMeta.routesUpdatedAt ? (",
"                    <div>",
"                      <dt>Routes updated</dt>",
"                      <dd>{formatPublishTimestamp(publishMeta.routesUpdatedAt)}</dd>",
"                    </div>",
"                  ) : null}",
"                </dl>",
"              ) : null}",
"              {publishWrittenFiles.length ? (",
"                <div className=\"canvas-workspace__publish-status-block\">",
"                  <strong>Written files</strong>",
"                  <ul className=\"canvas-workspace__publish-status-list\">",
"                    {publishWrittenFiles.map((filePath) => (",
"                      <li key={filePath}>{filePath}</li>",
"                    ))}",
"                  </ul>",
"                </div>",
"              ) : null}",
"              {publishFailures.length ? (",
"                <div className=\"canvas-workspace__publish-status-block\">",
"                  <strong>Failures</strong>",
"                  <ul className=\"canvas-workspace__publish-status-list\">",
"                    {publishFailures.map((failure, index) => {",
"                      const failureEntry =",
"                        failure && typeof failure === 'object' && !Array.isArray(failure)",
"                          ? failure",
"                          : { message: failure }",
"                      const key = failureEntry.file || failureEntry.directory || `failure-${index}`",
"                      return (",
"                        <li key={key}>",
"                          <span className=\"canvas-workspace__publish-failure-path\">",
"                            {failureEntry.file || failureEntry.directory || 'Unknown destination'}",
"                          </span>",
"                          {failureEntry.message ? (",
"                            <span className=\"canvas-workspace__publish-failure-message\"> -- {failureEntry.message}</span>",
"                          ) : null}",
"                        </li>",
"                      )",
"                    })}",
"                  </ul>",
"                </div>",
"              ) : null}",
"              {publishState.status === 'error' && publishInfo ? (",
"                <div className=\"canvas-workspace__publish-status-block\">",
"                  <strong>Details</strong>",
"                  {typeof publishInfo === 'object' ? (",
"                    <pre className=\"canvas-workspace__publish-note canvas-workspace__publish-note--pre\">",
"                      {JSON.stringify(publishInfo, null, 2)}",
"                    </pre>",
"                  ) : (",
"                    <p className=\"canvas-workspace__publish-note\">{String(publishInfo)}</p>",
"                  )}",
"                </div>",
"              ) : null}",
"              {publishState.status === 'error' && publishStatusCode ? (",
"                <div className=\"canvas-workspace__publish-status-block\">",
"                  <strong>Status code</strong>",
"                  <p className=\"canvas-workspace__publish-note\">{publishStatusCode}</p>",
"                </div>",
"              ) : null}",
"              {publishState.status === 'error' && publishAvailableTargets.length ? (",
"                <div className=\"canvas-workspace__publish-status-block\">",
"                  <strong>Configured targets</strong>",
"                  <p className=\"canvas-workspace__publish-note\">{publishAvailableTargets.join(', ')}</p>",
"                </div>",
"              ) : null}",
"            </section>",
"          </div>",
"",
"          <PropertiesPanel",
]
lines = lines[:start] + new_lines + lines[end:]
path.write_text("\n".join(lines) + "\n", encoding='utf-8')
