/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: crU26EU5sF5QWmZoX1Jupb
// Component: zNhmYUaGhfIE

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import Button from "../../Button"; // plasmic-import: 1lUB1-vmZT0U/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdPassword } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdPassword_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "../../components/plasmic/PlasmicShelves"; // plasmic-import: crU26EU5sF5QWmZoX1Jupb/projectModule
import { _useStyleTokens } from "../../components/plasmic/PlasmicGlobalVariant__GlobalStyles"; // plasmic-import: crU26EU5sF5QWmZoX1Jupb/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../../components/plasmic/plasmicStyles.module.css"; // plasmic-import: crU26EU5sF5QWmZoX1Jupb/projectcss
import sty from "./PlasmicLoginOpen.module.css"; // plasmic-import: zNhmYUaGhfIE/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 5b-tq9oITq4v/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: vm5JmdZvj5l-/icon

createPlasmicElementProxy;

export type PlasmicLoginOpen__VariantMembers = {
  open: "open";
};
export type PlasmicLoginOpen__VariantsArgs = {
  open?: SingleBooleanChoiceArg<"open">;
};
type VariantPropType = keyof PlasmicLoginOpen__VariantsArgs;
export const PlasmicLoginOpen__VariantProps = new Array<VariantPropType>(
  "open"
);

export type PlasmicLoginOpen__ArgsType = { fields?: any };
type ArgPropType = keyof PlasmicLoginOpen__ArgsType;
export const PlasmicLoginOpen__ArgProps = new Array<ArgPropType>("fields");

export type PlasmicLoginOpen__OverridesType = {
  root?: Flex__<"div">;
  column?: Flex__<"div">;
  login?: Flex__<typeof Button>;
  loginPanelWrapper?: Flex__<"form">;
  loginForm?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
  passwordInput?: Flex__<typeof AntdPassword>;
  loginSubmit?: Flex__<typeof AntdButton>;
  button?: Flex__<typeof Button>;
};

export interface DefaultLoginOpenProps {
  fields?: any;
  open?: SingleBooleanChoiceArg<"open">;
  className?: string;
}

const $$ = {};

function PlasmicLoginOpen__RenderFunc(props: {
  variants: PlasmicLoginOpen__VariantsArgs;
  args: PlasmicLoginOpen__ArgsType;
  overrides: PlasmicLoginOpen__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          fields: (() => {
            const __composite = [
              { label: null, name: null, inputType: "Text", rules: null },
              { inputType: null, label: null, name: null, rules: null }
            ];
            __composite["0"]["label"] = "Username";
            __composite["0"]["name"] = "username";
            __composite["0"]["rules"] = [
              { ruleType: "required", message: "Username is required" },

              { ruleType: "required" }
            ];

            __composite["1"]["inputType"] = "Password";
            __composite["1"]["label"] = "Password";
            __composite["1"]["name"] = "password";
            __composite["1"]["rules"] = [
              { ruleType: "required", message: "Password is required" }
            ];

            return __composite;
          })()
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "open",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.open
      },
      {
        path: "loginForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "loginForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "loginForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "loginForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "passwordInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdPassword_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootopen]: hasVariant($state, "open", "open") }
      )}
    >
      <div
        data-plasmic-name={"column"}
        data-plasmic-override={overrides.column}
        className={classNames(projectcss.all, sty.column, {
          [sty.columnopen]: hasVariant($state, "open", "open")
        })}
      >
        <Button
          data-plasmic-name={"login"}
          data-plasmic-override={overrides.login}
          className={classNames("__wab_instance", sty.login, {
            [sty.loginopen]: hasVariant($state, "open", "open")
          })}
          end={
            <ChevronDownIcon
              className={classNames(projectcss.all, sty.svg__gGwtF)}
              role={"img"}
            />
          }
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qJfJ4
              )}
            >
              {"Login"}
            </div>
          }
          onClick={async event => {
            const $steps = {};

            $steps["updateOpenOff"] = true
              ? (() => {
                  const actionArgs = { vgroup: "open", operation: 2 };
                  return (({ vgroup, value }) => {
                    if (typeof value === "string") {
                      value = [value];
                    }

                    const oldValue = $stateGet($state, vgroup);
                    $stateSet($state, vgroup, !oldValue);
                    return !oldValue;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateOpenOff"] != null &&
              typeof $steps["updateOpenOff"] === "object" &&
              typeof $steps["updateOpenOff"].then === "function"
            ) {
              $steps["updateOpenOff"] = await $steps["updateOpenOff"];
            }
          }}
        />

        <form
          data-plasmic-name={"loginPanelWrapper"}
          data-plasmic-override={overrides.loginPanelWrapper}
          className={classNames(projectcss.all, sty.loginPanelWrapper, {
            [sty.loginPanelWrapperopen]: hasVariant($state, "open", "open")
          })}
        >
          {(() => {
            const child$Props = {
              className: classNames("__wab_instance", sty.loginForm, {
                [sty.loginFormopen]: hasVariant($state, "open", "open")
              }),
              extendedOnValuesChange: async (...eventArgs: any) => {
                generateStateOnChangePropForCodeComponents(
                  $state,
                  "value",
                  ["loginForm", "value"],
                  FormWrapper_Helpers
                ).apply(null, eventArgs);
              },
              formItems: [
                { label: "Name", name: "name", inputType: "Text" },
                { label: "Message", name: "message", inputType: "Text Area" }
              ],
              labelCol: { span: 8, horizontalOnly: true },
              layout: "vertical",
              mode: "advanced",
              onFinish: async values => {
                const $steps = {};

                $steps["httpPost"] = true
                  ? (() => {
                      const actionArgs = {
                        dataOp: {
                          sourceId: "sUJmb7fto98xmfFEkWKXc8",
                          opId: "e5821529-7135-4dc7-ab53-9bc2503d4374",
                          userArgs: {},
                          cacheKey: null,
                          invalidatedKeys: [],
                          roleId: null
                        }
                      };
                      return (async ({ dataOp, continueOnError }) => {
                        try {
                          const response = await executePlasmicDataOp(dataOp, {
                            userAuthToken: dataSourcesCtx?.userAuthToken,
                            user: dataSourcesCtx?.user
                          });
                          await plasmicInvalidate(dataOp.invalidatedKeys);
                          return response;
                        } catch (e) {
                          if (!continueOnError) {
                            throw e;
                          }
                          return e;
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["httpPost"] != null &&
                  typeof $steps["httpPost"] === "object" &&
                  typeof $steps["httpPost"].then === "function"
                ) {
                  $steps["httpPost"] = await $steps["httpPost"];
                }
              },
              onIsSubmittingChange: async (...eventArgs: any) => {
                generateStateOnChangePropForCodeComponents(
                  $state,
                  "isSubmitting",
                  ["loginForm", "isSubmitting"],
                  FormWrapper_Helpers
                ).apply(null, eventArgs);
              },
              ref: ref => {
                $refs["loginForm"] = ref;
              },
              submitSlot: null,
              wrapperCol: { span: 16, horizontalOnly: true }
            };
            initializeCodeComponentStates(
              $state,
              [
                {
                  name: "value",
                  plasmicStateName: "loginForm.value"
                },
                {
                  name: "isSubmitting",
                  plasmicStateName: "loginForm.isSubmitting"
                }
              ],
              [],
              FormWrapper_Helpers ?? {},
              child$Props
            );

            return (
              <FormWrapper
                data-plasmic-name={"loginForm"}
                data-plasmic-override={overrides.loginForm}
                {...child$Props}
              >
                <FormItemWrapper
                  className={classNames("__wab_instance", sty.formField__b6XJn)}
                  label={"Username"}
                  name={"username"}
                  rules={[{ ruleType: "required" }]}
                >
                  {(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.input),
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["input", "value"],
                          AntdInput_Helpers
                        ).apply(null, eventArgs);
                      },
                      value: generateStateValueProp($state, ["input", "value"])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "input.value"
                        }
                      ],
                      [],
                      AntdInput_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdInput
                        data-plasmic-name={"input"}
                        data-plasmic-override={overrides.input}
                        {...child$Props}
                      />
                    );
                  })()}
                </FormItemWrapper>
                <FormItemWrapper
                  className={classNames("__wab_instance", sty.formField__lbaSk)}
                  label={"Password"}
                  name={"password"}
                  rules={[{ ruleType: "required" }]}
                >
                  {(() => {
                    const child$Props = {
                      className: classNames(
                        "__wab_instance",
                        sty.passwordInput
                      ),
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["passwordInput", "value"],
                          AntdPassword_Helpers
                        ).apply(null, eventArgs);
                      },
                      value: generateStateValueProp($state, [
                        "passwordInput",
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "passwordInput.value"
                        }
                      ],
                      [],
                      AntdPassword_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdPassword
                        data-plasmic-name={"passwordInput"}
                        data-plasmic-override={overrides.passwordInput}
                        {...child$Props}
                      />
                    );
                  })()}
                </FormItemWrapper>
                <AntdButton
                  data-plasmic-name={"loginSubmit"}
                  data-plasmic-override={overrides.loginSubmit}
                  className={classNames("__wab_instance", sty.loginSubmit, {
                    [sty.loginSubmitopen]: hasVariant($state, "open", "open")
                  })}
                  onClick={async () => {
                    const $steps = {};
                  }}
                  submitsForm={true}
                  type={"primary"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oAoY,
                      {
                        [sty.textopen__oAoY6PeG]: hasVariant(
                          $state,
                          "open",
                          "open"
                        )
                      }
                    )}
                  >
                    {"Submit"}
                  </div>
                </AntdButton>
              </FormWrapper>
            );
          })()}
        </form>
        <Button
          data-plasmic-name={"button"}
          data-plasmic-override={overrides.button}
          className={classNames("__wab_instance", sty.button, {
            [sty.buttonopen]: hasVariant($state, "open", "open")
          })}
          end={
            <ChevronDownIcon
              className={classNames(projectcss.all, sty.svg__mmiDy)}
              role={"img"}
            />
          }
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__usyVl
              )}
            >
              {"Text"}
            </div>
          }
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "column",
    "login",
    "loginPanelWrapper",
    "loginForm",
    "input",
    "passwordInput",
    "loginSubmit",
    "button"
  ],
  column: [
    "column",
    "login",
    "loginPanelWrapper",
    "loginForm",
    "input",
    "passwordInput",
    "loginSubmit",
    "button"
  ],
  login: ["login"],
  loginPanelWrapper: [
    "loginPanelWrapper",
    "loginForm",
    "input",
    "passwordInput",
    "loginSubmit"
  ],
  loginForm: ["loginForm", "input", "passwordInput", "loginSubmit"],
  input: ["input"],
  passwordInput: ["passwordInput"],
  loginSubmit: ["loginSubmit"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  column: "div";
  login: typeof Button;
  loginPanelWrapper: "form";
  loginForm: typeof FormWrapper;
  input: typeof AntdInput;
  passwordInput: typeof AntdPassword;
  loginSubmit: typeof AntdButton;
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginOpen__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginOpen__VariantsArgs;
    args?: PlasmicLoginOpen__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLoginOpen__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLoginOpen__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLoginOpen__ArgProps,
          internalVariantPropNames: PlasmicLoginOpen__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLoginOpen__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginOpen";
  } else {
    func.displayName = `PlasmicLoginOpen.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginOpen = Object.assign(
  // Top-level PlasmicLoginOpen renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    column: makeNodeComponent("column"),
    login: makeNodeComponent("login"),
    loginPanelWrapper: makeNodeComponent("loginPanelWrapper"),
    loginForm: makeNodeComponent("loginForm"),
    input: makeNodeComponent("input"),
    passwordInput: makeNodeComponent("passwordInput"),
    loginSubmit: makeNodeComponent("loginSubmit"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicLoginOpen
    internalVariantProps: PlasmicLoginOpen__VariantProps,
    internalArgProps: PlasmicLoginOpen__ArgProps
  }
);

export default PlasmicLoginOpen;
/* prettier-ignore-end */
