/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: crU26EU5sF5QWmZoX1Jupb

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_3L5NhBqtZ2Cb } from "../../plasmic-codegen/shelves/PlasmicGlobalVariant__Screen"; // plasmic-import: 3L5NHBqtZ2CB/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_3L5NhBqtZ2Cb
});
