/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: crU26EU5sF5QWmZoX1Jupb

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./PlasmicShelves"; // plasmic-import: crU26EU5sF5QWmZoX1Jupb/projectModule

import projectcss from "./plasmicStyles.module.css"; // plasmic-import: crU26EU5sF5QWmZoX1Jupb/projectcss

import plasmic_antd_5_hostless_css from "../../plasmic-codegen/antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss

const data = {
  base: `${projectcss.plasmic_tokens} ${plasmic_antd_5_hostless_css.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
