// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHomepage,
  DefaultHomepageProps
} from "./plasmic-codegen/shelves/PlasmicHomepage";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface HomepageProps extends DefaultHomepageProps {}

function Homepage_(props: HomepageProps, ref: HTMLElementRefOf<"div">) {
  return <PlasmicHomepage welcomeScreen={{ ref }} {...props} />;
}

const Homepage = React.forwardRef(Homepage_);
export default Homepage;
