// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useNavigate } from "react-router-dom";
import {
  PlasmicLoginOpen,
  DefaultLoginOpenProps
} from "./plasmic-codegen/shelves/PlasmicLoginOpen";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface LoginOpenProps extends DefaultLoginOpenProps {
  apiBase?: string;
  onLoginSuccess?: (payload: unknown) => void;
}

const trimTrailingSlash = (value?: string | null) => {
  if (!value) {
    return "";
  }
  return value.replace(/\/+$/, "");
};

function LoginOpen_(props: LoginOpenProps, ref: HTMLElementRefOf<"div">) {
  const { apiBase, onLoginSuccess, ...rest } = props;
  const navigate = useNavigate();
  const [submitting, setSubmitting] = React.useState(false);
  const rootElementRef = React.useRef<HTMLDivElement | null>(null);
  const submittingRef = React.useRef(false);

  const setRootRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      rootElementRef.current = node;
      if (typeof ref === "function") {
        ref(node);
      } else if (ref) {
        (ref as React.MutableRefObject<HTMLDivElement | null>).current = node;
      }
    },
    [ref]
  );

  const resolvedBase = React.useMemo(() => {
    if (apiBase) {
      return trimTrailingSlash(apiBase);
    }
    const envBase =
      typeof import.meta !== "undefined" && import.meta?.env?.VITE_API_BASE
        ? String(import.meta.env.VITE_API_BASE)
        : "";
    return trimTrailingSlash(envBase);
  }, [apiBase]);

  const loginUrl = React.useMemo(
    () => (resolvedBase ? `${resolvedBase}/api/login` : "/api/login"),
    [resolvedBase]
  );

  const runLogin = React.useCallback(
    async (username: string | undefined, password: string | undefined) => {
      const normalizedUser = (username ?? "").trim();
      const normalizedPass = password ?? "";

      if (!normalizedUser || !normalizedPass) {
        if (typeof window !== "undefined") {
          window.alert("Please provide both username and password.");
        }
        return;
      }

      if (submittingRef.current) {
        return;
      }

      submittingRef.current = true;
      setSubmitting(true);

      try {
        const response = await fetch(loginUrl, {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            username: normalizedUser,
            password: normalizedPass
          })
        });

        const payload = await response
          .json()
          .catch(() => ({} as Record<string, unknown>));

        if (!response.ok) {
          const message =
            (payload && typeof (payload as { error?: unknown }).error === "string"
              ? (payload as { error?: string }).error
              : undefined) ||
            response.statusText ||
            "Login failed";
          throw new Error(message);
        }

        if (
          payload &&
          typeof payload === "object" &&
          "token" in payload &&
          typeof (payload as { token?: unknown }).token === "string" &&
          typeof window !== "undefined"
        ) {
          try {
            window.localStorage.setItem(
              "token",
              (payload as { token: string }).token
            );
          } catch (err) {
            console.warn("Failed to persist auth token", err);
          }
        }

        onLoginSuccess?.(payload);
        navigate("/feed");
      } catch (error) {
        console.error("Login request failed", error);
        const message =
          error instanceof Error ? error.message : "Login failed";
        if (typeof window !== "undefined") {
          window.alert(message);
        }
      } finally {
        submittingRef.current = false;
        setSubmitting(false);
      }
    },
    [loginUrl, navigate, onLoginSuccess]
  );

  React.useEffect(() => {
    const root = rootElementRef.current;
    if (!root) {
      return;
    }

    const forms = Array.from(root.querySelectorAll<HTMLFormElement>("form"));
    if (!forms.length) {
      return;
    }

    const handleNativeSubmit = (event: Event) => {
      const target = event.target;
      if (!(target instanceof HTMLFormElement)) {
        return;
      }
      if (!root.contains(target)) {
        return;
      }

      event.preventDefault();

      const formData = new FormData(target);
      const username = formData.get("username");
      const password = formData.get("password");

      runLogin(
        typeof username === "string" ? username : undefined,
        typeof password === "string" ? password : undefined
      );
    };

    forms.forEach(form => {
      form.setAttribute("method", "post");
      form.setAttribute("action", "#");
      form.setAttribute("autocomplete", "off");
      form.addEventListener("submit", handleNativeSubmit);
    });

    return () => {
      forms.forEach(form => {
        form.removeEventListener("submit", handleNativeSubmit);
      });
    };
  }, [runLogin, props.open]);

  return (
    <PlasmicLoginOpen
      root={{ ref: setRootRef }}
      {...rest}
      overrides={{
        loginForm: {
          props: {
            onFinish: () => undefined
          }
        },
        loginPanelWrapper: {
          props: {
            method: "post",
            action: "#",
            noValidate: true
          }
        },
        loginSubmit: {
          props: {
            loading: submitting,
            disabled: submitting
          }
        }
      }}
    />
  );
}

const LoginOpen = React.forwardRef(LoginOpen_);
export default LoginOpen;
